export const COLOMBIA_DEPARTMENTS = [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlantico",
    "Bolivar",
    "Boyaca",
    "Caldas",
    "Caqueta",
    "Casanare",
    "Cauca",
    "Cesar",
    "Choco",
    "Cordoba",
    "Cundinamarca",
    "Guainia",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindio",
    "Risaralda",
    "San Andres y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupes",
    "Vichada",
];

export const COLOMBIA_CITIES_BY_DEPARTMENT: Record<string, string[]> = {
    Amazonas: ["Leticia"],
    Antioquia: ["Medellin", "Bello", "Envigado", "Itagui", "Rionegro", "Apartado"],
    Arauca: ["Arauca", "Saravena"],
    Atlantico: ["Barranquilla", "Soledad", "Malambo"],
    Bolivar: ["Cartagena", "Magangue"],
    Boyaca: ["Tunja", "Duitama", "Sogamoso"],
    Caldas: ["Manizales", "Villamaria"],
    Caqueta: ["Florencia"],
    Casanare: ["Yopal"],
    Cauca: ["Popayan"],
    Cesar: ["Valledupar"],
    Choco: ["Quibdo"],
    Cordoba: ["Monteria"],
    Cundinamarca: ["Bogota", "Soacha", "Chia", "Zipaquira"],
    Guainia: ["Inirida"],
    Guaviare: ["San Jose del Guaviare"],
    Huila: ["Neiva"],
    "La Guajira": ["Riohacha", "Maicao"],
    Magdalena: ["Santa Marta"],
    Meta: ["Villavicencio"],
    "Nariño": ["Pasto", "Ipiales"],
    "Norte de Santander": ["Cucuta", "Ocaña"],
    Putumayo: ["Mocoa"],
    Quindio: ["Armenia"],
    Risaralda: ["Pereira", "Dosquebradas"],
    "San Andres y Providencia": ["San Andres"],
    Santander: ["Bucaramanga", "Floridablanca", "Giron"],
    Sucre: ["Sincelejo"],
    Tolima: ["Ibague"],
    "Valle del Cauca": ["Cali", "Palmira", "Buenaventura"],
    Vaupes: ["Mitu"],
    Vichada: ["Puerto Carreno"],
};

